version: "3.8"

services:
  bot:
    build:
      context: ./bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./bot:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 1234K7F
      POSTGRES_DB: bredni_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  parser:
    build:
      context: ./parser
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./parser:/app

volumes:
  db_data:
